---
abstract: 'Decode from LaTeX to Unicode'
author:
  - 'François Charette <firmicus@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Decode
provides:
  LaTeX::Decode:
    file: lib/LaTeX/Decode.pm
    version: 0.03
  LaTeX::Decode::Data:
    file: lib/LaTeX/Decode/Data.pm
requires:
  File::Slurp: 0
  Unicode::Normalize: 0
  perl: 5.008
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.03
